import { Button } from "@/components/ui/button";

type ReportItem = { os?: number; tEquipSuporte: string; rp: string; nSerie: string; analiseTecnica: string };

export function BatchReport({ items, fallbackDescription, unit, date, technician, requester, pae, defect }: { items: ReportItem[]; fallbackDescription: string; unit: string; date: string; technician: string; requester: string; pae: string; defect: string }) {
  if (!items.length) return null;
  const print = () => {
    const win = window.open("", "_blank");
    if (!win) return;
    const rows = items.map(item => `<tr><td>${item.os || "—"}</td><td>${item.tEquipSuporte}</td><td>${item.rp}</td><td>${item.nSerie || "—"}</td><td>${item.analiseTecnica || fallbackDescription}</td></tr>`).join("");
    win.document.write(`<html><head><title>Relatório consolidado do lote</title><style>@page{size:A4 portrait;margin:12mm}body{font-family:Arial;padding:0;color:#000;font-size:9px}.header{display:flex;align-items:center;justify-content:space-between;border-bottom:1.2pt solid #000;padding-bottom:6px}.header img{width:72px;height:72px;object-fit:contain}.header-text{text-align:center;font-weight:bold;text-transform:uppercase;font-size:7px;line-height:1.25}.header-text strong{font-size:9px}.title{text-align:center;margin:12px 0 9px;font-size:11px}.meta{border:1px solid #000;padding:6px 8px;margin-bottom:8px;font-size:8px;line-height:1.7}.meta-row{display:flex;gap:14px;flex-wrap:wrap}.meta-item{white-space:nowrap}.meta-label{font-weight:bold;text-transform:uppercase;font-size:7px;color:#222}.table{width:100%;border-collapse:collapse;table-layout:fixed}.table th,.table td{border:1px solid #000;padding:4px;text-align:left;vertical-align:top;word-wrap:break-word}.table th{background:#eee;text-transform:uppercase;font-size:7px}.table td{font-size:8px;line-height:1.15}.table th:nth-child(1){width:7%}.table th:nth-child(2){width:20%}.table th:nth-child(3){width:12%}.table th:nth-child(4){width:14%}.footer{position:fixed;bottom:0;left:0;right:0;border-top:1px solid #000;padding-top:6px;text-align:center;font-size:7px;font-weight:bold}.footer p{margin:2px}</style></head><body><div class="header"><img src="${location.origin}/logo-pmpa.png"><div class="header-text"><div>Governo do Estado do Pará</div><div>Secretaria de Estado de Segurança Pública e Defesa Social</div><div>Polícia Militar do Pará</div><strong>Diretoria de Telemática</strong></div><img src="${location.origin}/Logo Ditel.jpeg"></div><h1 class="title">RELATÓRIO CONSOLIDADO DE EQUIPAMENTOS DO LOTE</h1><div class="meta"><div class="meta-row"><div class="meta-item"><span class="meta-label">Unidade:</span> ${unit || "—"}</div><div class="meta-item"><span class="meta-label">Data:</span> ${date || "—"}</div><div class="meta-item"><span class="meta-label">Técnico:</span> ${technician || "—"}</div></div><div class="meta-row"><div class="meta-item"><span class="meta-label">Solicitante:</span> ${requester || "—"}</div><div class="meta-item"><span class="meta-label">Nº PAE:</span> ${pae || "—"}</div><div class="meta-item"><span class="meta-label">Defeito reclamado:</span> ${defect || "—"}</div></div></div><table class="table"><thead><tr><th>O.S.</th><th>Equipamento</th><th>RP</th><th>Nº de série</th><th>Descrição do laudo/manutenção</th></tr></thead><tbody>${rows}</tbody></table><div class="footer"><p>Diretoria de Telemática - DITEL / PMPA</p><p>"A Diretoria de Telemática não possui peças de reposição ou suprimento para aquisição destas peças informadas"</p></div></body></html>`);
    win.document.body.insertAdjacentHTML("beforeend", '<div style="position:fixed;bottom:42px;left:12mm;right:12mm;display:flex;justify-content:space-between;gap:48px;text-align:center;font:700 7px Arial;text-transform:uppercase"><div style="width:45%;height:34px;border-top:1px solid #000;padding-top:5px">Técnico responsável<small style="display:block;font-size:6px;margin-top:4px">' + (technician || 'Nome do técnico') + ' - Diretoria de Telemática - PMPA</small></div><div style="width:45%;height:34px;border-top:1px solid #000;padding-top:5px">Assinatura do receptor / solicitante<small style="display:block;font-size:6px;margin-top:4px">Unidade receptora - PMPA</small></div></div>');
    win.document.close();
    win.onload = () => setTimeout(() => win.print(), 300);
    setTimeout(() => win.print(), 800);
  };
  return <Button type="button" className="w-full bg-[#004e9a] text-white shadow-md hover:bg-[#003b75] focus-visible:ring-2 focus-visible:ring-[#004e9a]/50" onClick={print}>Imprimir relatório do lote</Button>;
}
