import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useNavigate } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { API_BASE } from "@/lib/api-config";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EquipCombobox } from "@/components/EquipCombobox";
import { UnidadeCombobox } from "@/components/UnidadeCombobox";
import { AnaliseSugestoesMenu } from "@/components/AnaliseSugestoesMenu";
import { appendAnaliseSuggestion } from "@/lib/analiseSugestoes";
import { BatchReport } from "@/components/BatchReport";

type Item = { os?: number; rp: string; nSerie: string; tEquipSuporte: string; atendimento: string; situacao: string; analiseTecnica: string };
type BatchRecord = { os: number; rp: string };
type Draft = { dataEnt: string; unidade: string; tecnico: string; solicitante: string; nPae: string; defeitoRecl: string; atendimento: string; tipo: string; analiseTecnica: string; items: Item[]; updatedAt: string };
const KEY = "cadastro-lote-draft";
const blank = (tipo = "", atendimento = "MANUTENCAO", situacao = "PENDENTE") => ({ rp: "", nSerie: "", tEquipSuporte: tipo, atendimento, situacao, analiseTecnica: "" });

export default function CadastroLote() {
  const navigate = useNavigate();
  const [dataEnt, setDataEnt] = useState(""); const [unidade, setUnidade] = useState(""); const [tecnico, setTecnico] = useState(""); const [solicitante, setSolicitante] = useState(""); const [nPae, setNPae] = useState(""); const [defeitoRecl, setDefeitoRecl] = useState("");
  const [atendimento, setAtendimento] = useState("MANUTENCAO"); const [situacao, setSituacao] = useState("PENDENTE"); const [tipo, setTipo] = useState(""); const [analiseTecnica, setAnaliseTecnica] = useState("");
  const [items, setItems] = useState<Item[]>([]); const [savedItems, setSavedItems] = useState<Item[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [reviewing, setReviewing] = useState(false);
  useEffect(() => { const raw = localStorage.getItem(KEY); if (!raw) return; try { const d = JSON.parse(raw) as Draft; if (d.items?.length && confirm(`Cadastro em lote não concluído encontrado (${d.items.length} equipamentos). Continuar?`)) { setDataEnt(d.dataEnt); setUnidade(d.unidade); setTecnico(d.tecnico); setAtendimento(d.atendimento); setTipo(d.tipo); setAnaliseTecnica(d.analiseTecnica); setItems(d.items); } else if (d.items?.length) localStorage.removeItem(KEY); } catch { localStorage.removeItem(KEY); } }, []);
  useEffect(() => { if (!items.length && !dataEnt && !unidade && !tecnico && !analiseTecnica) return; const d: Draft = { dataEnt, unidade, tecnico, solicitante, nPae, defeitoRecl, atendimento, tipo, analiseTecnica, items, updatedAt: new Date().toISOString() }; localStorage.setItem(KEY, JSON.stringify(d)); }, [dataEnt, unidade, tecnico, atendimento, tipo, analiseTecnica, items]);
  const errors = useMemo(() => { const e: string[] = []; if (!dataEnt) e.push("Data"); if (!unidade) e.push("Unidade"); if (!tecnico) e.push("Técnico"); if (!tipo) e.push("Tipo de equipamento"); if (!analiseTecnica.trim()) e.push("Análise Técnica"); items.forEach((i, n) => { if (!i.rp.trim()) e.push(`Equipamento ${n + 1}: RP`); }); return e; }, [dataEnt, unidade, tecnico, tipo, analiseTecnica, items]);
  const add = () => setItems(v => [...v, { ...blank(tipo, atendimento, situacao), analiseTecnica }]); const update = (n: number, patch: Partial<Item>) => setItems(v => v.map((item, i) => i === n ? { ...item, ...patch } : item));
  async function save() { setMessage(""); if (errors.length) { setMessage(`Corrija: ${errors.join(", ")}`); return; } if (new Set(items.map(i => i.nSerie.trim().toLocaleLowerCase()).filter(Boolean)).size !== items.map(i => i.nSerie.trim().toLocaleLowerCase()).filter(Boolean).length) { setMessage("Patrimônios preenchidos não podem se repetir no lote."); return; } setSaving(true); try { const token = localStorage.getItem("ditel_token"); const res = await fetch(`${API_BASE}/servicos/lote`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ equipamentos: items.map(i => ({ dataEnt, unidade, tecnico, servico: (i.atendimento || atendimento) === "LAUDO" ? "LAUDO" : (i.situacao || situacao), solicitante, nPae, defeitoRecl, tEquipSuporte: i.tEquipSuporte, analiseTecnica: i.analiseTecnica || analiseTecnica, rp: i.rp, nSerie: i.nSerie })) }) }); const data = await res.json() as { count: number; records: BatchRecord[]; error?: string }; if (!res.ok) throw new Error(data.error || "Não foi possível salvar o lote."); localStorage.removeItem(KEY); setSavedItems(items.map((item, index) => ({ ...item, os: data.records[index]?.os }))); setItems([]); setMessage(`${data.count} equipamento(s) cadastrado(s): ${data.records.map((r) => `O.S. ${r.os} — RP ${r.rp}`).join("; ")}`); } catch (e) { setMessage(e instanceof Error ? e.message : "Erro de rede. O rascunho foi preservado."); } finally { setSaving(false); } }
  return <main className="mx-auto max-w-3xl space-y-6 p-4 md:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Button type="button" variant="ghost" size="sm" onClick={() => navigate("/")} aria-label="Voltar ao início" className="gap-1"><ArrowLeft className="h-4 w-4" /><span>Voltar</span></Button><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Equipamentos</p><h1 className="text-2xl font-black">Cadastro em lote</h1></div></div><Button asChild variant="outline"><Link to="/cadastro">Cadastro individual</Link></Button></div>
    <section className="space-y-4 rounded-2xl border bg-white p-4 shadow-sm"><h2 className="font-black uppercase tracking-widest">Dados gerais</h2><div className="grid gap-3 sm:grid-cols-2"><div><label htmlFor="data-ent" className="text-xs font-bold">Data de entrada</label><Input id="data-ent" type="date" value={dataEnt} onChange={e => setDataEnt(e.target.value)} /></div><div><label className="text-xs font-bold" htmlFor="unidade">Unidade</label><UnidadeCombobox value={unidade} onChange={setUnidade} /></div><div><label htmlFor="tecnico" className="text-xs font-bold">Técnico</label><Input id="tecnico" placeholder="Técnico" value={tecnico} onChange={e => setTecnico(e.target.value)} /></div><div><label htmlFor="solicitante" className="text-xs font-bold">Solicitante (opcional)</label><Input id="solicitante" value={solicitante} onChange={e => setSolicitante(e.target.value)} /></div><div><label htmlFor="n-pae" className="text-xs font-bold">Nº do PAE (opcional)</label><Input id="n-pae" value={nPae} onChange={e => setNPae(e.target.value)} /></div><div className="sm:col-span-2"><label htmlFor="defeito-recl" className="text-xs font-bold">Defeito reclamado (opcional)</label><Textarea id="defeito-recl" value={defeitoRecl} onChange={e => setDefeitoRecl(e.target.value)} /></div><div><label htmlFor="atendimento" className="text-xs font-bold">Atendimento</label><select id="atendimento" className="h-10 w-full rounded-md border px-3" value={atendimento} onChange={e => setAtendimento(e.target.value)}><option value="MANUTENCAO">Manutenção</option><option value="LAUDO">Laudo</option></select></div><div><label className="text-xs font-bold">Tipo padrão</label><EquipCombobox value={tipo} onChange={setTipo} /></div>{atendimento === "MANUTENCAO" && <div><label className="text-xs font-bold" htmlFor="situacao">Situação padrão</label><select id="situacao" className="h-10 w-full rounded-md border px-3" value={situacao} onChange={e => setSituacao(e.target.value)}><option value="PENDENTE">Pendente</option><option value="PRONTO">Pronto</option></select></div>}</div><div><div className="mb-2 flex items-center justify-between"><label htmlFor="analise-padrao" className="text-xs font-bold text-[#004e9a]">Análise Técnica padrão</label><AnaliseSugestoesMenu onSelect={suggestion => { const result = appendAnaliseSuggestion(analiseTecnica, suggestion); if (!result.duplicate) setAnaliseTecnica(result.value); }} /></div><Textarea id="analise-padrao" placeholder="Análise Técnica padrão" value={analiseTecnica} onChange={e => setAnaliseTecnica(e.target.value)} /></div></section>
    <section className="space-y-3"><h2 className="font-black uppercase tracking-widest">Equipamentos ({items.length})</h2>{items.map((item, n) => <article key={n} className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><h3 className="font-bold">Equipamento {String(n + 1).padStart(2, "0")}</h3><Button type="button" variant="ghost" onClick={() => setItems(v => v.filter((_, i) => i !== n))}>Remover</Button></div><div className="grid gap-3 sm:grid-cols-2"><div><label className="text-xs font-bold" htmlFor={`atendimento-${n}`}>Tipo de atendimento</label><select id={`atendimento-${n}`} aria-label={`Tipo de atendimento do equipamento ${n + 1}`} className="h-10 w-full rounded-md border px-3" value={item.atendimento || atendimento} onChange={e => update(n, { atendimento: e.target.value })}><option value="MANUTENCAO">Manutenção</option><option value="LAUDO">Laudo</option></select></div><div><label className="text-xs font-bold">Tipo de equipamento</label><EquipCombobox value={item.tEquipSuporte} onChange={v => update(n, { tEquipSuporte: v })} /></div>{(item.atendimento || atendimento) === "MANUTENCAO" && <div><label className="text-xs font-bold" htmlFor={`situacao-${n}`}>Situação</label><select id={`situacao-${n}`} className="h-10 w-full rounded-md border px-3" value={item.situacao || situacao} onChange={e => update(n, { situacao: e.target.value })}><option value="PENDENTE">Pendente</option><option value="PRONTO">Pronto</option></select></div>}</div><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="RP obrigatório" value={item.rp} onChange={e => update(n, { rp: e.target.value })} /><Input placeholder="Patrimônio (opcional)" value={item.nSerie} onChange={e => update(n, { nSerie: e.target.value })} /></div><div><div className="mb-2 flex items-center justify-between"><label className="text-xs font-bold text-[#004e9a]">Análise Técnica do equipamento</label><AnaliseSugestoesMenu onSelect={suggestion => { const result = appendAnaliseSuggestion(item.analiseTecnica, suggestion); if (!result.duplicate) update(n, { analiseTecnica: result.value }); }} /></div><Textarea placeholder="Análise individual (herda a padrão)" value={item.analiseTecnica} onChange={e => update(n, { analiseTecnica: e.target.value })} /></div></article>)}<Button type="button" onClick={add}>+ Adicionar equipamento</Button></section>
    <BatchReport items={savedItems} fallbackDescription={analiseTecnica} unit={unidade} date={dataEnt} technician={tecnico} requester={solicitante} pae={nPae} defect={defeitoRecl} />
    {message && <p role="status" aria-live="polite" className="rounded-lg bg-slate-100 p-3 text-sm font-medium">{message}</p>}
    {reviewing && <section className="rounded-2xl border bg-slate-50 p-4"><h2 className="font-black uppercase tracking-widest">Revisar lote</h2><p className="mt-2 text-sm">{items.length} equipamento(s) · {unidade || "Unidade não informada"}</p><ul className="mt-3 space-y-1 text-sm">{items.map((item, n) => <li key={n}>Equipamento {n + 1}: {item.atendimento === "LAUDO" ? "Laudo" : `Manutenção — ${item.situacao === "PRONTO" ? "Pronto" : "Pendente"}`} — RP {item.rp} — Patrimônio {item.nSerie}</li>)}</ul></section>}
    <Button className="w-full" disabled={saving || !items.length} onClick={() => reviewing ? save() : setReviewing(true)}>{saving ? "Salvando..." : reviewing ? `Cadastrar ${items.length} equipamento(s)` : "Revisar lote"}</Button>
  </main>;
}
