import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { API_BASE } from "@/lib/api-config";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { EquipCombobox } from "@/components/EquipCombobox";
import { UnidadeCombobox } from "@/components/UnidadeCombobox";
import { AnaliseSugestoesMenu } from "@/components/AnaliseSugestoesMenu";
import { appendAnaliseSuggestion } from "@/lib/analiseSugestoes";

type Item = { rp: string; nSerie: string; tEquipSuporte: string; analiseTecnica: string };
type BatchRecord = { os: number; rp: string };
type Draft = { dataEnt: string; unidade: string; tecnico: string; atendimento: string; tipo: string; analiseTecnica: string; items: Item[]; updatedAt: string };
const KEY = "cadastro-lote-draft";
const blank = (tipo = "") => ({ rp: "", nSerie: "", tEquipSuporte: tipo, analiseTecnica: "" });

export default function CadastroLote() {
  const [dataEnt, setDataEnt] = useState(""); const [unidade, setUnidade] = useState(""); const [tecnico, setTecnico] = useState("");
  const [atendimento, setAtendimento] = useState("MANUTENCAO"); const [tipo, setTipo] = useState(""); const [analiseTecnica, setAnaliseTecnica] = useState("");
  const [items, setItems] = useState<Item[]>([]); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [reviewing, setReviewing] = useState(false);
  useEffect(() => { const raw = localStorage.getItem(KEY); if (!raw) return; try { const d = JSON.parse(raw) as Draft; if (d.items?.length && confirm(`Cadastro em lote não concluído encontrado (${d.items.length} equipamentos). Continuar?`)) { setDataEnt(d.dataEnt); setUnidade(d.unidade); setTecnico(d.tecnico); setAtendimento(d.atendimento); setTipo(d.tipo); setAnaliseTecnica(d.analiseTecnica); setItems(d.items); } else if (d.items?.length) localStorage.removeItem(KEY); } catch { localStorage.removeItem(KEY); } }, []);
  useEffect(() => { if (!items.length && !dataEnt && !unidade && !tecnico && !analiseTecnica) return; const d: Draft = { dataEnt, unidade, tecnico, atendimento, tipo, analiseTecnica, items, updatedAt: new Date().toISOString() }; localStorage.setItem(KEY, JSON.stringify(d)); }, [dataEnt, unidade, tecnico, atendimento, tipo, analiseTecnica, items]);
  const errors = useMemo(() => { const e: string[] = []; if (!dataEnt) e.push("Data"); if (!unidade) e.push("Unidade"); if (!tecnico) e.push("Técnico"); if (!tipo) e.push("Tipo de equipamento"); if (!analiseTecnica.trim()) e.push("Análise Técnica"); items.forEach((i, n) => { if (!i.rp.trim() || !i.nSerie.trim()) e.push(`Equipamento ${n + 1}: RP e Patrimônio`); }); return e; }, [dataEnt, unidade, tecnico, tipo, analiseTecnica, items]);
  const add = () => setItems(v => [...v, { ...blank(tipo), analiseTecnica }]); const update = (n: number, patch: Partial<Item>) => setItems(v => v.map((item, i) => i === n ? { ...item, ...patch } : item));
  async function save() { setMessage(""); if (errors.length) { setMessage(`Corrija: ${errors.join(", ")}`); return; } if (new Set(items.map(i => i.rp.trim().toLocaleLowerCase())).size !== items.length || new Set(items.map(i => i.nSerie.trim().toLocaleLowerCase())).size !== items.length) { setMessage("RP e Patrimônio não podem se repetir no lote."); return; } setSaving(true); try { const token = localStorage.getItem("ditel_token"); const res = await fetch(`${API_BASE}/servicos/lote`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ equipamentos: items.map(i => ({ dataEnt, unidade, tecnico, servico: atendimento, tEquipSuporte: i.tEquipSuporte, analiseTecnica: i.analiseTecnica || analiseTecnica, rp: i.rp, nSerie: i.nSerie })) }) }); const data = await res.json() as { count: number; records: BatchRecord[]; error?: string }; if (!res.ok) throw new Error(data.error || "Não foi possível salvar o lote."); localStorage.removeItem(KEY); setItems([]); setMessage(`${data.count} equipamento(s) cadastrado(s): ${data.records.map((r) => `O.S. ${r.os} — RP ${r.rp}`).join("; ")}`); } catch (e) { setMessage(e instanceof Error ? e.message : "Erro de rede. O rascunho foi preservado."); } finally { setSaving(false); } }
  return <main className="mx-auto max-w-3xl space-y-6 p-4 md:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Equipamentos</p><h1 className="text-2xl font-black">Cadastro em lote</h1></div><Button asChild variant="outline"><Link to="/cadastro">Cadastro individual</Link></Button></div>
    <section className="space-y-4 rounded-2xl border bg-white p-4 shadow-sm"><h2 className="font-black uppercase tracking-widest">Dados gerais</h2><div className="grid gap-3 sm:grid-cols-2"><div><label htmlFor="data-ent" className="text-xs font-bold">Data de entrada</label><Input id="data-ent" type="date" value={dataEnt} onChange={e => setDataEnt(e.target.value)} /></div><div><label className="text-xs font-bold" htmlFor="unidade">Unidade</label><UnidadeCombobox value={unidade} onChange={setUnidade} /></div><div><label htmlFor="tecnico" className="text-xs font-bold">Técnico</label><Input id="tecnico" placeholder="Técnico" value={tecnico} onChange={e => setTecnico(e.target.value)} /></div><div><label htmlFor="atendimento" className="text-xs font-bold">Atendimento</label><select id="atendimento" className="h-10 w-full rounded-md border px-3" value={atendimento} onChange={e => setAtendimento(e.target.value)}><option value="MANUTENCAO">Manutenção</option><option value="LAUDO">Laudo</option></select></div><div><label className="text-xs font-bold">Tipo padrão</label><EquipCombobox value={tipo} onChange={setTipo} /></div></div><div><div className="mb-2 flex items-center justify-between"><label htmlFor="analise-padrao" className="text-xs font-bold text-[#004e9a]">Análise Técnica padrão</label><AnaliseSugestoesMenu onSelect={suggestion => { const result = appendAnaliseSuggestion(analiseTecnica, suggestion); if (!result.duplicate) setAnaliseTecnica(result.value); }} /></div><Textarea id="analise-padrao" placeholder="Análise Técnica padrão" value={analiseTecnica} onChange={e => setAnaliseTecnica(e.target.value)} /></div></section>
    <section className="space-y-3"><h2 className="font-black uppercase tracking-widest">Equipamentos ({items.length})</h2>{items.map((item, n) => <article key={n} className="space-y-3 rounded-2xl border bg-white p-4 shadow-sm"><div className="flex justify-between"><h3 className="font-bold">Equipamento {String(n + 1).padStart(2, "0")}</h3><Button type="button" variant="ghost" onClick={() => setItems(v => v.filter((_, i) => i !== n))}>Remover</Button></div><EquipCombobox value={item.tEquipSuporte} onChange={v => update(n, { tEquipSuporte: v })} /><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="RP obrigatório" value={item.rp} onChange={e => update(n, { rp: e.target.value })} /><Input placeholder="Patrimônio obrigatório" value={item.nSerie} onChange={e => update(n, { nSerie: e.target.value })} /></div><div><div className="mb-2 flex items-center justify-between"><label className="text-xs font-bold text-[#004e9a]">Análise Técnica do equipamento</label><AnaliseSugestoesMenu onSelect={suggestion => { const result = appendAnaliseSuggestion(item.analiseTecnica, suggestion); if (!result.duplicate) update(n, { analiseTecnica: result.value }); }} /></div><Textarea placeholder="Análise individual (herda a padrão)" value={item.analiseTecnica} onChange={e => update(n, { analiseTecnica: e.target.value })} /></div></article>)}<Button type="button" onClick={add}>+ Adicionar equipamento</Button></section>
    {message && <p role="status" aria-live="polite" className="rounded-lg bg-slate-100 p-3 text-sm font-medium">{message}</p>}
    {reviewing && <section className="rounded-2xl border bg-slate-50 p-4"><h2 className="font-black uppercase tracking-widest">Revisar lote</h2><p className="mt-2 text-sm">{items.length} equipamento(s) · {unidade || "Unidade não informada"} · {atendimento === "LAUDO" ? "Laudo" : "Manutenção"}</p><ul className="mt-3 space-y-1 text-sm">{items.map((item, n) => <li key={n}>Equipamento {n + 1}: RP {item.rp} — Patrimônio {item.nSerie}</li>)}</ul></section>}
    <Button className="w-full" disabled={saving || !items.length} onClick={() => reviewing ? save() : setReviewing(true)}>{saving ? "Salvando..." : reviewing ? `Cadastrar ${items.length} equipamento(s)` : "Revisar lote"}</Button>
  </main>;
}
