export type BatchIndividualItem = { os?: number; rp: string; nSerie: string; tEquipSuporte: string; atendimento: string; situacao: string; analiseTecnica: string };
export type BatchIndividualData = { items: BatchIndividualItem[]; unit: string; date: string; technician: string; requester: string; pae: string; defect: string };

const escapeHtml = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[char] || char));
const dateBR = (value: string) => value ? (value.includes("/") ? value : value.split("-").reverse().join("/")) : "—";

export function buildBatchIndividualDocument(data: BatchIndividualData, origin = "") {
  const location = { origin };
  const pages = data.items.map(item => {
    const isMaintenance = item.atendimento === "MANUTENCAO";
    const title = isMaintenance ? "RELATÓRIO DE MANUTENÇÃO" : "RELATÓRIO DE LAUDO TÉCNICO";
    return `<section class="os-page"><header class="header"><img src="${location.origin}/logo-pmpa.png" alt="PMPA"><div class="header-text">GOVERNO DO ESTADO DO PARÁ<br>SECRETARIA DE ESTADO DE SEGURANÇA PÚBLICA E DEFESA SOCIAL<br>POLÍCIA MILITAR DO PARÁ<br><strong>DIRETORIA DE TELEMÁTICA</strong></div><img src="${location.origin}/Logo Ditel.jpeg" alt="DITEL"></header><h1>${title}</h1><div class="os-line"><strong>O.S.: ${escapeHtml(item.os || "—")}</strong><span>Suporte: ${escapeHtml(item.tEquipSuporte)}</span><span>Unidade: ${escapeHtml(data.unit || "—")}</span></div><div class="fields"><div><b>Nº PAE</b><span>${escapeHtml(data.pae || "—")}</span></div><div><b>RP/PM</b><span>${escapeHtml(item.rp || "—")}</span></div><div><b>Nº SÉRIE</b><span>${escapeHtml(item.nSerie || "—")}</span></div><div><b>SOLICITANTE</b><span>${escapeHtml(data.requester || "—")}</span></div><div><b>DATA ENTRADA</b><span>${dateBR(data.date)}</span></div></div><div class="content"><h2>DEFEITO RECLAMADO</h2><p>${escapeHtml(data.defect || "Não informado.")}</p><h2>ANÁLISE TÉCNICA</h2><p>${escapeHtml(item.analiseTecnica || "Sob análise.")}</p>${isMaintenance ? `<h2>SITUAÇÃO</h2><p>${escapeHtml(item.situacao || "PENDENTE")}</p>` : `<h2>LAUDO TÉCNICO</h2><p>${escapeHtml(item.analiseTecnica || "")}</p>`}</div><div class="signatures"><div><b>ODIRSON MICHAEL TAVARES DA SILVA - 2º TEN PM RG 44443</b><small>RESPONDENDO PELAS SEÇÕES DE TELECOMUNICAÇÃO E SUPORTE AO USUÁRIO</small></div><div><b>RECEBEDOR DO EQUIPAMENTO</b><small>UNIDADE RECEPTORA - PMPA</small></div></div><footer>Diretoria de Telemática - DITEL / PMPA<br>"A Diretoria de Telemática não possui peças de reposição ou suprimento para aquisição destas peças informadas"<br><span>Técnico responsável: ${escapeHtml(data.technician || "—")}</span></footer></section>`;
  }).join("");
  return `<html><head><title>O.S. individuais do lote</title><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#000}.os-page{width:210mm;height:297mm;padding:15mm 17mm 14mm;display:flex;flex-direction:column;page-break-after:always}.os-page:last-child{page-break-after:auto}.header{display:flex;align-items:center;justify-content:space-between;border-bottom:1.2pt solid #000;padding-bottom:7mm}.header img{width:25mm;height:25mm;object-fit:contain}.header-text{text-align:center;font-size:8px;font-weight:bold;line-height:1.35}.header-text strong{font-size:10px}.os-page h1{text-align:center;font-size:14px;margin:9mm 0 7mm;letter-spacing:.5px}.os-line{display:flex;gap:16px;border-bottom:1px solid #000;padding-bottom:3mm;font-size:11px}.os-line span{flex:1}.fields{display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin:7mm 0;font-size:9px}.fields div{display:flex;flex-direction:column;gap:3px}.fields b,.content h2{font-size:8px}.fields span{min-height:18px}.content{flex:1;border-top:1px solid #000;padding-top:5mm;font-size:11px}.content h2{margin:4mm 0 1.5mm}.content p{margin:0;min-height:20px;white-space:pre-wrap}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:18mm;text-align:center;font-size:8px;margin-bottom:14mm}.signatures>div{border-top:1px solid #000;padding-top:2mm}.signatures small{display:block;margin-top:2mm;font-size:7px}footer{border-top:1px solid #000;padding-top:3mm;text-align:center;font-size:7px;font-weight:bold;line-height:1.5}footer span{display:block;margin-top:3mm;font-weight:normal}</style></head><body>${pages}</body></html>`;
}
